language: node_js

node_js:
- "node"

branches:
  only:
  - master

before_install:
- npm install -g hexo

install:
- npm install

before_script:
- git config --global user.name 'Kyle M Hall'
- git config --global user.email 'kyle@bywatersolutions.com'

script:
- git log -1 --pretty=oneline | grep 'Site auto-updated' || hexo generate
- git add -A docs
- git status
- git commit -m 'Site auto-updated'
- git status
- git remote add github https://$GH_TOKEN@github.com/bywatersolutions/devs.bywatersolutions.com
- git fetch github
- git push github HEAD:master
